[package]
name = "needle"
version = "0.1.2"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
env_logger = "0.11.5"
log = "0.4.22"
needle-core = { version = "0.1.3", path = "needle-core" }
pollster = "0.4.0"
winit = { version = "0.29", features = ["rwh_05"] }

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3.9", features = ["wincon"]}
