[package]
name = "needle"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
eframe = "0.27.2"
egui = "0.27.2"
egui-winit = "0.27.2"
needle-core = { version = "0.1.0", path = "lib/needle-core" }
